### ISSUE TITLE
With fluent/fluenbit-operator, generator fails with: Expected token IDENTIFIER but got "null" while parsing parameter

### ISSUE THREAD

**Issue by davidovich** [jsonnet-libs/k8s#116]
I am trying to generate a jsonnet library from https://github.com/fluent/fluentbit-operator, and the generation fails around a seemingly valid  OpenAPI property named `"null"`.

Here is an excerpt from https://raw.githubusercontent.com/fluent/fluentbit-operator/master/manifests/setup/setup.yaml used to generate the lib:

```yaml
...
              matchRegex:
                description: A regular expression to match against the tags of incoming
                  records. Use this option if you want to use the full regex syntax.
                type: string
              "null":
                description: Null defines Null Output configuration.
                type: object
...
```

The process seems to proceed as expected, but the `k8s-gen` fails with 

```
671:14-18 Expected token IDENTIFIER but got "null" while parsing parameter:
```

Going to the specified line shows (notice `withNull(null): `,  `{ null: null }` and `{ null+: null }` which are invalid):

```jsonnet
...
    '#withMatchRegex':: d.fn(help="\"A regular expression to match against the tags of incoming records. Use this option if you want to use the full regex syntax.\"", args=[d.arg(name="matchRegex", type=d.T.string)]),
    withMatchRegex(matchRegex): { spec+: { matchRegex: matchRegex } },
    '#withNull':: d.fn(help="\"Null defines Null Output configuration.\"", args=[d.arg(name="null", type=d.T.object)]),
    withNull(null): { spec+: { null: null } },
    '#withNullMixin':: d.fn(help="\"Null defines Null Output configuration.\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name="null", type=d.T.object)]),
    withNullMixin(null): { spec+: { null+: null } },
    '#withRetry_limit':: d.fn(help="\"RetryLimit represents configuration for the scheduler which can be set independently on each output section. This option allows to disable retries or impose a limit to try N times and then discard the data after reaching that limit.\"", args=[d.arg(name="retry_limit", type=d.T.string)]),
...
```

Obviously `null` is a keyword in jsonnet, but I am not sure what the generation should look like. I have tried modifying the `pkg/model/modifiers.go:fnArg` sanitizing function to mimic the pattern and return "Null", but then I get another error:

```
671:32-36 Unexpected: "null" while parsing field definition:

... 

    withNull(Null): { spec+: { null: Null } },
```

More info on the fluent Null output type: https://docs.fluentbit.io/manual/pipeline/outputs/null

I believe the field name that should also be quoted (additionally to parameter sanitizing), but I was not able to find where that was generated.

I think this is what we want:

```jsonnet
   withNull(Null) : { spec+: { 'null': Null } }
```
