### ISSUE TITLE
Unable to create a service without defining a selector.

### ISSUE THREAD

**Issue by Jezza** [jsonnet-libs/k8s#80]
It's possible to define a service without a selector if you're defining it for an external service.

https://github.com/jsonnet-libs/k8s/blob/master/libs/k8s/custom/core/core.libsonnet#L126

https://kubernetes.io/docs/concepts/services-networking/service/#services-without-selectors

I'm unable to use the nice `new()` function, as it requires a selector argument.

**Comment by xvzf** [comment]
Hey @Jezza thank you very much!

I don't think changing the function `new` is an option as it'd break a lot of code-bases.
Wdyt about adding a new mixing for `newWithoutSelector` just inheriting the `super.new` function?

**Comment by Duologic** [comment]
Neither selector or ports are required on a Service, we could modify the function with empty values: `new(name, selector='', ports=[])` and have some if/else checks in the function.

**Comment by mmusnjak** [comment]
I'm considering how to update this, and my first thought is :
```
        new(name, selector={}, ports=[])::
          super.new(name)
          + (if selector == {} then assert ports == [] : 'Service without selectors should not have ports'; super.spec.withType('ExternalName') else {})
          + (if selector != {} then assert ports != [] : 'Service with selectors should have ports'; super.spec.withSelector(selector) + super.spec.withPorts(ports) else {}),
```

which can be used like this:
```
local k = (import 'gen/github.com/jsonnet-libs/k8s-libsonnet/1.23/main.libsonnet');

{
    externalService: k.core.v1.service.new("external"),
    // selectorWithoutPorts: k.core.v1.service.new("selectorWithoutPorts", {selector: "value"},[] ) ,
    // portsWithoutSelector: k.core.v1.service.new("portsWithoutSelector", {}, [8080]),
    regularService: k.core.v1.service.new("regular", {selector: "value"}, [8080]) 
}
```

and the output will be :
```yaml
externalService:
  apiVersion: v1
  kind: Service
  metadata:
    name: external
  spec:
    type: ExternalName
regularService:
  apiVersion: v1
  kind: Service
  metadata:
    name: regular
  spec:
    ports:
      - 8080
    selector:
      selector: value
```

Uncommenting the middle two lines will fail, each with its own error message.

I'm worried if this is: 
* too strict?
* going too far with automatically setting the service type?
* missing some cases?
